from decimal import Decimal
from pathlib import Path
from typing import TypedDict

from pydantic import TypeAdapter

from .contracts import LocalizedText, Product

ROOT = Path(__file__).resolve().parents[3]
ARTIFACT_PATH = ROOT / "artifacts" / "demo" / "catalog.json"
PUBLIC_PATH = ROOT / "apps" / "web" / "public" / "catalog.json"


class PinnedProduct(TypedDict):
    id: int
    title: str
    name_es: str
    description: str
    description_es: str
    category: str
    price: float
    discountPercentage: float
    rating: float
    stock: int
    thumbnail: str
    tags: list[str]


# Curated snapshots from https://dummyjson.com/docs/products. Values are pinned
# so generation remains deterministic and the deployed application has no API dependency.
PINNED_PRODUCTS: tuple[PinnedProduct, ...] = (
    {
        "id": 1,
        "title": "Essence Mascara Lash Princess",
        "name_es": "Máscara de pestañas Essence Lash Princess",
        "description": "The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.",
        "description_es": "Máscara de pestañas de larga duración con efecto de volumen y alargamiento.",
        "category": "beauty",
        "price": 9.99,
        "discountPercentage": 10.48,
        "rating": 2.56,
        "stock": 99,
        "thumbnail": "https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/thumbnail.webp",
        "tags": ["beauty", "mascara"],
    },
    {
        "id": 2,
        "title": "Eyeshadow Palette with Mirror",
        "name_es": "Paleta de sombras con espejo",
        "description": "The Eyeshadow Palette with Mirror offers a versatile range of eyeshadow shades for creating stunning eye looks. With a built-in mirror, it's convenient for on-the-go makeup application.",
        "description_es": "Paleta versátil de sombras con espejo incorporado para retoques fuera de casa.",
        "category": "beauty",
        "price": 19.99,
        "discountPercentage": 18.19,
        "rating": 2.86,
        "stock": 34,
        "thumbnail": "https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/thumbnail.webp",
        "tags": ["beauty", "eyeshadow"],
    },
    {
        "id": 3,
        "title": "Powder Canister",
        "name_es": "Polvo fijador",
        "description": "The Powder Canister is a finely milled setting powder designed to set makeup and control shine. With a lightweight and translucent formula, it provides a smooth and matte finish.",
        "description_es": "Polvo fijador ligero y translúcido que ayuda a controlar el brillo y deja un acabado mate.",
        "category": "beauty",
        "price": 14.99,
        "discountPercentage": 9.84,
        "rating": 4.64,
        "stock": 89,
        "thumbnail": "https://cdn.dummyjson.com/product-images/beauty/powder-canister/thumbnail.webp",
        "tags": ["beauty", "face powder"],
    },
    {
        "id": 4,
        "title": "Red Lipstick",
        "name_es": "Labial rojo",
        "description": "The Red Lipstick is a classic and bold choice for adding a pop of color to your lips. With a creamy and pigmented formula, it provides a vibrant and long-lasting finish.",
        "description_es": "Labial rojo cremoso y pigmentado con un acabado intenso y duradero.",
        "category": "beauty",
        "price": 12.99,
        "discountPercentage": 12.16,
        "rating": 4.36,
        "stock": 91,
        "thumbnail": "https://cdn.dummyjson.com/product-images/beauty/red-lipstick/thumbnail.webp",
        "tags": ["beauty", "lipstick"],
    },
    {
        "id": 6,
        "title": "Calvin Klein CK One",
        "name_es": "Calvin Klein CK One",
        "description": "CK One by Calvin Klein is a classic unisex fragrance, known for its fresh and clean scent. It's a versatile fragrance suitable for everyday wear.",
        "description_es": "Fragancia unisex clásica con aroma fresco y limpio para el uso diario.",
        "category": "fragrances",
        "price": 49.99,
        "discountPercentage": 1.89,
        "rating": 4.37,
        "stock": 29,
        "thumbnail": "https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/thumbnail.webp",
        "tags": ["fragrances", "perfumes"],
    },
    {
        "id": 7,
        "title": "Chanel Coco Noir Eau De",
        "name_es": "Chanel Coco Noir Eau de",
        "description": "Coco Noir by Chanel is an elegant and mysterious fragrance, featuring notes of grapefruit, rose, and sandalwood. Perfect for evening occasions.",
        "description_es": "Fragancia elegante con notas de pomelo, rosa y sándalo, pensada para ocasiones nocturnas.",
        "category": "fragrances",
        "price": 129.99,
        "discountPercentage": 16.51,
        "rating": 4.26,
        "stock": 58,
        "thumbnail": "https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/thumbnail.webp",
        "tags": ["fragrances", "perfumes"],
    },
    {
        "id": 8,
        "title": "Dior J'adore",
        "name_es": "Dior J’adore",
        "description": "J'adore by Dior is a luxurious and floral fragrance, known for its blend of ylang-ylang, rose, and jasmine. It embodies femininity and sophistication.",
        "description_es": "Fragancia floral con ylang-ylang, rosa y jazmín, de carácter sofisticado.",
        "category": "fragrances",
        "price": 89.99,
        "discountPercentage": 14.72,
        "rating": 3.8,
        "stock": 98,
        "thumbnail": "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/thumbnail.webp",
        "tags": ["fragrances", "perfumes"],
    },
    {
        "id": 9,
        "title": "Dolce Shine Eau de",
        "name_es": "Dolce Shine Eau de",
        "description": "Dolce Shine by Dolce & Gabbana is a vibrant and fruity fragrance, featuring notes of mango, jasmine, and blonde woods. It's a joyful and youthful scent.",
        "description_es": "Fragancia frutal con notas de mango, jazmín y maderas claras.",
        "category": "fragrances",
        "price": 69.99,
        "discountPercentage": 0.62,
        "rating": 3.96,
        "stock": 4,
        "thumbnail": "https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/thumbnail.webp",
        "tags": ["fragrances", "perfumes"],
    },
    {
        "id": 11,
        "title": "Annibale Colombo Bed",
        "name_es": "Cama Annibale Colombo",
        "description": "The Annibale Colombo Bed is a luxurious and elegant bed frame, crafted with high-quality materials for a comfortable and stylish bedroom.",
        "description_es": "Estructura de cama elegante fabricada con materiales de alta calidad.",
        "category": "furniture",
        "price": 1899.99,
        "discountPercentage": 8.57,
        "rating": 4.77,
        "stock": 88,
        "thumbnail": "https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/thumbnail.webp",
        "tags": ["furniture", "beds"],
    },
    {
        "id": 12,
        "title": "Annibale Colombo Sofa",
        "name_es": "Sofá Annibale Colombo",
        "description": "The Annibale Colombo Sofa is a sophisticated and comfortable seating option, featuring exquisite design and premium upholstery for your living room.",
        "description_es": "Sofá cómodo con diseño sofisticado y tapizado de primera calidad.",
        "category": "furniture",
        "price": 2499.99,
        "discountPercentage": 14.4,
        "rating": 3.92,
        "stock": 60,
        "thumbnail": "https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/thumbnail.webp",
        "tags": ["furniture", "sofas"],
    },
    {
        "id": 13,
        "title": "Bedside Table African Cherry",
        "name_es": "Mesa de noche African Cherry",
        "description": "The Bedside Table in African Cherry is a stylish and functional addition to your bedroom, providing convenient storage space and a touch of elegance.",
        "description_es": "Mesa de noche funcional con espacio de almacenamiento y acabado en cerezo africano.",
        "category": "furniture",
        "price": 299.99,
        "discountPercentage": 19.09,
        "rating": 2.87,
        "stock": 64,
        "thumbnail": "https://cdn.dummyjson.com/product-images/furniture/bedside-table-african-cherry/thumbnail.webp",
        "tags": ["furniture", "bedside tables"],
    },
    {
        "id": 14,
        "title": "Knoll Saarinen Executive Conference Chair",
        "name_es": "Silla ejecutiva Knoll Saarinen",
        "description": "The Knoll Saarinen Executive Conference Chair is a modern and ergonomic chair, perfect for your office or conference room with its timeless design.",
        "description_es": "Silla ergonómica de diseño moderno para oficina o sala de reuniones.",
        "category": "furniture",
        "price": 499.99,
        "discountPercentage": 2.01,
        "rating": 4.88,
        "stock": 26,
        "thumbnail": "https://cdn.dummyjson.com/product-images/furniture/knoll-saarinen-executive-conference-chair/thumbnail.webp",
        "tags": ["furniture", "office chairs"],
    },
    {
        "id": 16,
        "title": "Apple",
        "name_es": "Manzana",
        "description": "Fresh and crisp apples, perfect for snacking or incorporating into various recipes.",
        "description_es": "Manzanas frescas y crujientes para comer solas o incorporar en distintas recetas.",
        "category": "groceries",
        "price": 1.99,
        "discountPercentage": 12.62,
        "rating": 4.19,
        "stock": 8,
        "thumbnail": "https://cdn.dummyjson.com/product-images/groceries/apple/thumbnail.webp",
        "tags": ["fruits"],
    },
    {
        "id": 17,
        "title": "Beef Steak",
        "name_es": "Bistec de res",
        "description": "High-quality beef steak, great for grilling or cooking to your preferred level of doneness.",
        "description_es": "Corte de carne de res apto para parrilla o cocción al punto preferido.",
        "category": "groceries",
        "price": 12.99,
        "discountPercentage": 9.61,
        "rating": 4.47,
        "stock": 86,
        "thumbnail": "https://cdn.dummyjson.com/product-images/groceries/beef-steak/thumbnail.webp",
        "tags": ["meat"],
    },
    {
        "id": 18,
        "title": "Cat Food",
        "name_es": "Alimento para gatos",
        "description": "Nutritious cat food formulated to meet the dietary needs of your feline friend.",
        "description_es": "Alimento nutritivo formulado para cubrir las necesidades diarias de los gatos.",
        "category": "groceries",
        "price": 8.99,
        "discountPercentage": 9.58,
        "rating": 3.13,
        "stock": 46,
        "thumbnail": "https://cdn.dummyjson.com/product-images/groceries/cat-food/thumbnail.webp",
        "tags": ["pet supplies", "cat food"],
    },
    {
        "id": 19,
        "title": "Chicken Meat",
        "name_es": "Carne de pollo",
        "description": "Fresh and tender chicken meat, suitable for various culinary preparations.",
        "description_es": "Carne de pollo fresca y tierna para distintas preparaciones culinarias.",
        "category": "groceries",
        "price": 9.99,
        "discountPercentage": 13.7,
        "rating": 3.19,
        "stock": 97,
        "thumbnail": "https://cdn.dummyjson.com/product-images/groceries/chicken-meat/thumbnail.webp",
        "tags": ["meat"],
    },
    {
        "id": 43,
        "title": "Decoration Swing",
        "name_es": "Columpio decorativo",
        "description": "The Decoration Swing is a charming addition to your home decor. Crafted with intricate details, it adds a touch of elegance and whimsy to any room.",
        "description_es": "Pieza decorativa con detalles trabajados para dar un toque lúdico al hogar.",
        "category": "home-decoration",
        "price": 59.99,
        "discountPercentage": 10.41,
        "rating": 3.16,
        "stock": 47,
        "thumbnail": "https://cdn.dummyjson.com/product-images/home-decoration/decoration-swing/thumbnail.webp",
        "tags": ["home decor", "swing"],
    },
    {
        "id": 44,
        "title": "Family Tree Photo Frame",
        "name_es": "Marco de fotos familiar",
        "description": "The Family Tree Photo Frame is a sentimental and stylish way to display your cherished family memories. With multiple photo slots, it tells the story of your loved ones.",
        "description_es": "Marco con varios espacios para exhibir fotografías y recuerdos familiares.",
        "category": "home-decoration",
        "price": 29.99,
        "discountPercentage": 14.87,
        "rating": 4.53,
        "stock": 77,
        "thumbnail": "https://cdn.dummyjson.com/product-images/home-decoration/family-tree-photo-frame/thumbnail.webp",
        "tags": ["home decor", "photo frame"],
    },
    {
        "id": 45,
        "title": "House Showpiece Plant",
        "name_es": "Planta decorativa",
        "description": "The House Showpiece Plant is an artificial plant that brings a touch of nature to your home without the need for maintenance. It adds greenery and style to any space.",
        "description_es": "Planta artificial que aporta verde al espacio sin necesidad de mantenimiento.",
        "category": "home-decoration",
        "price": 39.99,
        "discountPercentage": 7.46,
        "rating": 4.67,
        "stock": 28,
        "thumbnail": "https://cdn.dummyjson.com/product-images/home-decoration/house-showpiece-plant/thumbnail.webp",
        "tags": ["home decor", "artificial plants"],
    },
    {
        "id": 46,
        "title": "Plant Pot",
        "name_es": "Macetero",
        "description": "The Plant Pot is a stylish container for your favorite plants. With a sleek design, it complements your indoor or outdoor garden, adding a modern touch to your plant display.",
        "description_es": "Macetero de diseño simple para plantas de interior o exterior.",
        "category": "home-decoration",
        "price": 14.99,
        "discountPercentage": 6.84,
        "rating": 3.01,
        "stock": 59,
        "thumbnail": "https://cdn.dummyjson.com/product-images/home-decoration/plant-pot/thumbnail.webp",
        "tags": ["home decor", "plant accessories"],
    },
    {
        "id": 48,
        "title": "Bamboo Spatula",
        "name_es": "Espátula de bambú",
        "description": "The Bamboo Spatula is a versatile kitchen tool made from eco-friendly bamboo. Ideal for flipping, stirring, and serving various dishes.",
        "description_es": "Utensilio de bambú para voltear, mezclar y servir alimentos.",
        "category": "kitchen-accessories",
        "price": 7.99,
        "discountPercentage": 2.84,
        "rating": 3.27,
        "stock": 37,
        "thumbnail": "https://cdn.dummyjson.com/product-images/kitchen-accessories/bamboo-spatula/thumbnail.webp",
        "tags": ["kitchen tools", "utensils"],
    },
    {
        "id": 49,
        "title": "Black Aluminium Cup",
        "name_es": "Taza de aluminio negra",
        "description": "The Black Aluminium Cup is a stylish and durable cup suitable for both hot and cold beverages. Its sleek black design adds a modern touch to your drinkware collection.",
        "description_es": "Taza resistente para bebidas frías o calientes con acabado negro.",
        "category": "kitchen-accessories",
        "price": 5.99,
        "discountPercentage": 15.65,
        "rating": 4.46,
        "stock": 75,
        "thumbnail": "https://cdn.dummyjson.com/product-images/kitchen-accessories/black-aluminium-cup/thumbnail.webp",
        "tags": ["drinkware", "cups"],
    },
    {
        "id": 50,
        "title": "Black Whisk",
        "name_es": "Batidor negro",
        "description": "The Black Whisk is a kitchen essential for whisking and beating ingredients. Its ergonomic handle and sleek design make it a practical and stylish tool.",
        "description_es": "Utensilio de cocina con mango ergonómico para batir y mezclar ingredientes.",
        "category": "kitchen-accessories",
        "price": 9.99,
        "discountPercentage": 10.24,
        "rating": 3.9,
        "stock": 73,
        "thumbnail": "https://cdn.dummyjson.com/product-images/kitchen-accessories/black-whisk/thumbnail.webp",
        "tags": ["kitchen tools", "utensils"],
    },
    {
        "id": 51,
        "title": "Boxed Blender",
        "name_es": "Licuadora compacta",
        "description": "The Boxed Blender is a powerful and compact blender perfect for smoothies, shakes, and more. Its convenient design and multiple functions make it a versatile kitchen appliance.",
        "description_es": "Licuadora potente y compacta para batidos y preparaciones cotidianas.",
        "category": "kitchen-accessories",
        "price": 39.99,
        "discountPercentage": 7.26,
        "rating": 4.56,
        "stock": 9,
        "thumbnail": "https://cdn.dummyjson.com/product-images/kitchen-accessories/boxed-blender/thumbnail.webp",
        "tags": ["kitchen appliances", "blenders"],
    },
    {
        "id": 78,
        "title": "Apple MacBook Pro 14 Inch Space Grey",
        "name_es": "Apple MacBook Pro 14 pulgadas gris espacial",
        "description": "The MacBook Pro 14 Inch in Space Grey is a powerful and sleek laptop, featuring Apple's M1 Pro chip for exceptional performance and a stunning Retina display.",
        "description_es": "Portátil de 14 pulgadas con chip M1 Pro y pantalla Retina.",
        "category": "laptops",
        "price": 1999.99,
        "discountPercentage": 4.69,
        "rating": 3.65,
        "stock": 24,
        "thumbnail": "https://cdn.dummyjson.com/product-images/laptops/apple-macbook-pro-14-inch-space-grey/thumbnail.webp",
        "tags": ["laptops", "apple"],
    },
    {
        "id": 79,
        "title": "Asus Zenbook Pro Dual Screen Laptop",
        "name_es": "Asus Zenbook Pro de doble pantalla",
        "description": "The Asus Zenbook Pro Dual Screen Laptop is a high-performance device with dual screens, providing productivity and versatility for creative professionals.",
        "description_es": "Portátil de alto rendimiento con dos pantallas para trabajo creativo y multitarea.",
        "category": "laptops",
        "price": 1799.99,
        "discountPercentage": 11.14,
        "rating": 3.95,
        "stock": 45,
        "thumbnail": "https://cdn.dummyjson.com/product-images/laptops/asus-zenbook-pro-dual-screen-laptop/thumbnail.webp",
        "tags": ["laptops"],
    },
    {
        "id": 80,
        "title": "Huawei Matebook X Pro",
        "name_es": "Huawei Matebook X Pro",
        "description": "The Huawei Matebook X Pro is a slim and stylish laptop with a high-resolution touchscreen display, offering a premium experience for users on the go.",
        "description_es": "Portátil delgado con pantalla táctil de alta resolución para trabajar en movimiento.",
        "category": "laptops",
        "price": 1399.99,
        "discountPercentage": 9.38,
        "rating": 4.98,
        "stock": 75,
        "thumbnail": "https://cdn.dummyjson.com/product-images/laptops/huawei-matebook-x-pro/thumbnail.webp",
        "tags": ["laptops"],
    },
    {
        "id": 81,
        "title": "Lenovo Yoga 920",
        "name_es": "Lenovo Yoga 920",
        "description": "The Lenovo Yoga 920 is a 2-in-1 convertible laptop with a flexible hinge, allowing you to use it as a laptop or tablet, offering versatility and portability.",
        "description_es": "Portátil convertible 2 en 1 que puede utilizarse también como tableta.",
        "category": "laptops",
        "price": 1099.99,
        "discountPercentage": 6.55,
        "rating": 2.86,
        "stock": 40,
        "thumbnail": "https://cdn.dummyjson.com/product-images/laptops/lenovo-yoga-920/thumbnail.webp",
        "tags": ["laptops"],
    },
    {
        "id": 83,
        "title": "Blue & Black Check Shirt",
        "name_es": "Camisa a cuadros azul y negra",
        "description": "The Blue & Black Check Shirt is a stylish and comfortable men's shirt featuring a classic check pattern. Made from high-quality fabric, it's suitable for both casual and semi-formal occasions.",
        "description_es": "Camisa cómoda con patrón clásico a cuadros para ocasiones casuales o semiformal.",
        "category": "mens-shirts",
        "price": 29.99,
        "discountPercentage": 15.35,
        "rating": 3.64,
        "stock": 38,
        "thumbnail": "https://cdn.dummyjson.com/product-images/mens-shirts/blue-&-black-check-shirt/thumbnail.webp",
        "tags": ["clothing", "men's shirts"],
    },
    {
        "id": 84,
        "title": "Gigabyte Aorus Men Tshirt",
        "name_es": "Camiseta Gigabyte Aorus",
        "description": "The Gigabyte Aorus Men Tshirt is a cool and casual shirt for gaming enthusiasts. With the Aorus logo and sleek design, it's perfect for expressing your gaming style.",
        "description_es": "Camiseta casual con logotipo Aorus para aficionados a los videojuegos.",
        "category": "mens-shirts",
        "price": 24.99,
        "discountPercentage": 0.94,
        "rating": 3.18,
        "stock": 90,
        "thumbnail": "https://cdn.dummyjson.com/product-images/mens-shirts/gigabyte-aorus-men-tshirt/thumbnail.webp",
        "tags": ["clothing", "men's t-shirts"],
    },
    {
        "id": 85,
        "title": "Man Plaid Shirt",
        "name_es": "Camisa a cuadros para hombre",
        "description": "The Man Plaid Shirt is a timeless and versatile men's shirt with a classic plaid pattern. Its comfortable fit and casual style make it a wardrobe essential for various occasions.",
        "description_es": "Camisa versátil de corte cómodo con diseño clásico a cuadros.",
        "category": "mens-shirts",
        "price": 34.99,
        "discountPercentage": 19.5,
        "rating": 3.46,
        "stock": 82,
        "thumbnail": "https://cdn.dummyjson.com/product-images/mens-shirts/man-plaid-shirt/thumbnail.webp",
        "tags": ["clothing", "men's shirts"],
    },
    {
        "id": 86,
        "title": "Man Short Sleeve Shirt",
        "name_es": "Camisa de manga corta para hombre",
        "description": "The Man Short Sleeve Shirt is a breezy and stylish option for warm days. With a comfortable fit and short sleeves, it's perfect for a laid-back yet polished look.",
        "description_es": "Camisa ligera de manga corta para días cálidos y uso casual.",
        "category": "mens-shirts",
        "price": 19.99,
        "discountPercentage": 6.83,
        "rating": 2.9,
        "stock": 2,
        "thumbnail": "https://cdn.dummyjson.com/product-images/mens-shirts/man-short-sleeve-shirt/thumbnail.webp",
        "tags": ["clothing", "men's shirts"],
    },
    {
        "id": 121,
        "title": "iPhone 5s",
        "name_es": "iPhone 5s",
        "description": "The iPhone 5s is a classic smartphone known for its compact design and advanced features during its release. While it's an older model, it still provides a reliable user experience.",
        "description_es": "Smartphone compacto de Apple con las funciones representativas de su generación.",
        "category": "smartphones",
        "price": 199.99,
        "discountPercentage": 12.91,
        "rating": 2.83,
        "stock": 25,
        "thumbnail": "https://cdn.dummyjson.com/product-images/smartphones/iphone-5s/thumbnail.webp",
        "tags": ["smartphones", "apple"],
    },
    {
        "id": 122,
        "title": "iPhone 6",
        "name_es": "iPhone 6",
        "description": "The iPhone 6 is a stylish and capable smartphone with a larger display and improved performance. It introduced new features and design elements, making it a popular choice in its time.",
        "description_es": "Smartphone de Apple con pantalla amplia y un diseño clásico.",
        "category": "smartphones",
        "price": 299.99,
        "discountPercentage": 6.69,
        "rating": 3.41,
        "stock": 60,
        "thumbnail": "https://cdn.dummyjson.com/product-images/smartphones/iphone-6/thumbnail.webp",
        "tags": ["smartphones", "apple"],
    },
    {
        "id": 123,
        "title": "iPhone 13 Pro",
        "name_es": "iPhone 13 Pro",
        "description": "The iPhone 13 Pro is a cutting-edge smartphone with a powerful camera system, high-performance chip, and stunning display. It offers advanced features for users who demand top-notch technology.",
        "description_es": "Smartphone de alto rendimiento con sistema avanzado de cámaras y pantalla de gran calidad.",
        "category": "smartphones",
        "price": 1099.99,
        "discountPercentage": 9.37,
        "rating": 4.12,
        "stock": 56,
        "thumbnail": "https://cdn.dummyjson.com/product-images/smartphones/iphone-13-pro/thumbnail.webp",
        "tags": ["smartphones", "apple"],
    },
    {
        "id": 124,
        "title": "iPhone X",
        "name_es": "iPhone X",
        "description": "The iPhone X is a flagship smartphone featuring a bezel-less OLED display, facial recognition technology (Face ID), and impressive performance. It represents a milestone in iPhone design and innovation.",
        "description_es": "Smartphone de Apple con pantalla OLED, Face ID y diseño sin botón frontal.",
        "category": "smartphones",
        "price": 899.99,
        "discountPercentage": 19.59,
        "rating": 2.51,
        "stock": 37,
        "thumbnail": "https://cdn.dummyjson.com/product-images/smartphones/iphone-x/thumbnail.webp",
        "tags": ["smartphones", "apple"],
    },
    {
        "id": 137,
        "title": "American Football",
        "name_es": "Balón de fútbol americano",
        "description": "The American Football is a classic ball used in American football games. It is designed for throwing and catching, making it an essential piece of equipment for the sport.",
        "description_es": "Balón diseñado para lanzar y recibir en partidos de fútbol americano.",
        "category": "sports-accessories",
        "price": 19.99,
        "discountPercentage": 4.93,
        "rating": 4.91,
        "stock": 53,
        "thumbnail": "https://cdn.dummyjson.com/product-images/sports-accessories/american-football/thumbnail.webp",
        "tags": ["sports equipment", "american football"],
    },
    {
        "id": 138,
        "title": "Baseball Ball",
        "name_es": "Pelota de béisbol",
        "description": "The Baseball Ball is a standard baseball used in baseball games. It features a durable leather cover and is designed for pitching, hitting, and fielding in the game of baseball.",
        "description_es": "Pelota reglamentaria con cubierta resistente para lanzar, batear y fildear.",
        "category": "sports-accessories",
        "price": 8.99,
        "discountPercentage": 1.71,
        "rating": 2.57,
        "stock": 100,
        "thumbnail": "https://cdn.dummyjson.com/product-images/sports-accessories/baseball-ball/thumbnail.webp",
        "tags": ["sports equipment", "baseball"],
    },
    {
        "id": 139,
        "title": "Baseball Glove",
        "name_es": "Guante de béisbol",
        "description": "The Baseball Glove is a protective glove worn by baseball players. It is designed to catch and field the baseball, providing players with comfort and control during the game.",
        "description_es": "Guante protector diseñado para atrapar la pelota con comodidad y control.",
        "category": "sports-accessories",
        "price": 24.99,
        "discountPercentage": 2.9,
        "rating": 3.96,
        "stock": 22,
        "thumbnail": "https://cdn.dummyjson.com/product-images/sports-accessories/baseball-glove/thumbnail.webp",
        "tags": ["sports equipment", "baseball"],
    },
    {
        "id": 140,
        "title": "Basketball",
        "name_es": "Balón de básquetbol",
        "description": "The Basketball is a standard ball used in basketball games. It is designed for dribbling, shooting, and passing in the game of basketball, suitable for both indoor and outdoor play.",
        "description_es": "Balón apto para driblar, lanzar y pasar tanto en interior como al aire libre.",
        "category": "sports-accessories",
        "price": 14.99,
        "discountPercentage": 7.44,
        "rating": 4.66,
        "stock": 75,
        "thumbnail": "https://cdn.dummyjson.com/product-images/sports-accessories/basketball/thumbnail.webp",
        "tags": ["sports equipment", "basketball"],
    },
)

CATEGORY_PREFIX = {
    "beauty": "BEA",
    "fragrances": "FRA",
    "furniture": "FUR",
    "groceries": "GRO",
    "home-decoration": "HOM",
    "kitchen-accessories": "KIT",
    "laptops": "LAP",
    "mens-shirts": "MEN",
    "smartphones": "PHO",
    "sports-accessories": "SPT",
}


def build_catalog() -> list[Product]:
    products: list[Product] = []
    for index, row in enumerate(PINNED_PRODUCTS):
        price = Decimal(str(row["price"])).quantize(Decimal("0.01"))
        discount = Decimal(str(row["discountPercentage"])) / Decimal(100)
        original_price = (price / (Decimal(1) - discount)).quantize(Decimal("0.01"))
        products.append(
            Product(
                id=f"prd_dummy_{row['id']:03d}",
                sku=f"{CATEGORY_PREFIX[row['category']]}-{row['id']:04d}",
                name=LocalizedText(en=row["title"], es=row["name_es"]),
                description=LocalizedText(en=row["description"], es=row["description_es"]),
                category=row["category"],
                subcategory=row["tags"][0] if row["tags"] else None,
                price=price,
                original_price=original_price,
                in_stock=row["stock"] > 0,
                inventory_quantity=row["stock"],
                rating=row["rating"],
                review_count=3,
                image_url=row["thumbnail"],
                tags=row["tags"],
                popularity_score=100 - index,
            )
        )
    return products


def generate() -> None:
    payload = TypeAdapter(list[Product]).dump_json(build_catalog(), indent=2)
    for path in (ARTIFACT_PATH, PUBLIC_PATH):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(payload + b"\n")


def validate() -> None:
    catalog = TypeAdapter(list[Product]).validate_json(ARTIFACT_PATH.read_bytes())
    if len({product.id for product in catalog}) != len(catalog):
        raise ValueError("Product IDs must be unique")
    if ARTIFACT_PATH.read_bytes() != PUBLIC_PATH.read_bytes():
        raise ValueError("Published catalog differs from canonical artifact")


if __name__ == "__main__":
    generate()
    validate()
